name: events
description: "Events project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_html: ^3.0.0
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.1"
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/appIcon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icons/appIcon.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/icons/
    - assets/audio/

  fonts:
    - family: cocon-next-arabic
      fonts:
        - asset: assets/fonts/cocon-next-arabic.ttf
    - family: Hacen Beirut
      fonts:
        - asset: assets/fonts/Hacen Beirut.ttf
